sonar.projectKey=FleetSec-Lab
sonar.projectName=FleetSec-Lab

sonar.sources=app
sonar.sourceEncoding=UTF-8
sonar.python.version=3.13

sonar.exclusions=\
**/.venv/**,\
**/__pycache__/**,\
**/*.pyc,\
**/reports/**,\
**/.git/**,\
**/.terraform/**,\
**/terraform.tfstate

sonar.coverage.exclusions=\
**/scripts/**