env:
  contexts:
    - name: FleetSec
      urls:
        - http://localhost:8082

  parameters:
    failOnError: false

jobs:

  - type: openapi
    parameters:
      apiUrl: http://localhost:8082/openapi.json

  - type: activeScan

  - type: report
    parameters:
      template: traditional-html
      reportDir: /zap/wrk
      reportFile: zap-report.html